version: '3'

services:
  dovly-legacy:
    container_name: dovly-legacy
    build: .
    image: dovly-legacy:dev
    environment:
      VIRTUAL_HOST: dovly-legacy.proj
    external_links:
      - mysqldb