version: '3'

services:
  mysqldb:
    image: mysqldb:dev
    networks:
      - dev_network
    #restart: always
    ports:
      - 3306:3306 # this needs to 127.0.0.1:3306:3306 if connection from host machine is needed
    environment:
      MYSQL_ROOT_HOST: '%' # this should not be enabled on production environments
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'local'
      MYSQL_PASSWORD: 'local'
    volumes:
      - ./data:/var/lib/mysql #this will fail on Docker for Windows b/c read here: https://dev.mysql.com/doc/refman/5.7/en/deploy-mysql-nonlinux-docker.html
networks:
  dev_network:
    external:
      name: dev_network