version: '3'

services:
  mysqldb:
    image: mysqldb:dev
    networks:
      - dev_network
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    volumes:
      - ./data:/var/lib/mysql
networks:
  dev_network:
    external:
      name: dev_network